dartcms/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.i18n import JavaScriptCatalog

js_info_dict = {
    'packages': ('dartcms',),
}

app_name = 'dartcms'

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    url(r'^', include('dartcms.apps.dashboard.urls', namespace='dashboard')),
    url(r'^auth/', include('dartcms.apps.auth.urls', namespace='auth')),

    url(r'^filemanager/', include('dartcms.apps.filemanager.urls', namespace='filemanager')),
    url(r'^dict-(?P<module_slug>[a-z_-]{3,50})/',
        include('dartcms.apps.dicts.urls', namespace='dicts')),
]

if 'dartcms.apps.users.groups' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^user-groups/', include('dartcms.apps.users.groups.urls', namespace='user_groups')), ]

if 'dartcms.apps.siteusers' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^site-users/', include('dartcms.apps.siteusers.urls', namespace='siteusers')), ]

if 'dartcms.apps.users' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^cms-users/', include('dartcms.apps.users.urls', namespace='users')), ]

if 'dartcms.apps.pages' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^sitemap/', include('dartcms.apps.pages.urls', namespace='pages')), ]

if 'dartcms.apps.feeds' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^feeds/', include('dartcms.apps.feeds.urls', namespace='feeds')), ]

if 'dartcms.apps.sitesettings' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^sitesettings/', include('dartcms.apps.sitesettings.urls', namespace='sitesettings')), ]

if 'dartcms.apps.ads' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^ad/', include('dartcms.apps.ads.ad.urls', namespace='ad')),
        url(r'^adplace/', include('dartcms.apps.ads.adplace.urls', namespace='adplace')),
        url(r'^adsection/', include('dartcms.apps.ads.adsection.urls', namespace='adsection')), ]

if 'dartcms.apps.feedback' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^feedback/', include('dartcms.apps.feedback.urls', namespace='feedback')), ]

if 'dartcms.apps.shop' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^shop-catalog/', include('dartcms.apps.shop.catalog.urls', namespace='shop-catalog')),
        url(r'^shop-orders/', include('dartcms.apps.shop.order.urls', namespace='shop-orders')), ]

additional_apps = getattr(settings, 'DARTCMS_ADDITIONAL_APPS_URLPATTERNS', [])

if additional_apps:
    additional_patterns = []
    for app in additional_apps:
        additional_patterns.append(url(r'^%s/' % app[0], include(app[1], namespace=app[2])))

    urlpatterns += additional_patterns

dartcms/templates/dartcms/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} DartCMS</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block core_css %}
        <link rel="stylesheet" href="{% static 'dartcms/assets/font-awesome/css/font-awesome.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'dartcms/assets/boostrap/dist/css/bootstrap.css' %}"/>

        <link rel="stylesheet" href="{% static 'dartcms/assets/jasny-bootstrap/css/jasny-bootstrap.min.css' %}"/>
        <link rel="stylesheet"
              href="{% static 'dartcms/css/lib/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}"/>
        <link rel="stylesheet" href="{% static 'dartcms/assets/pnotify/pnotify.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'dartcms/assets/jquery-modal/jquery-modal.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'dartcms/css/style.css' %}"/>
    {% endblock %}
    {% block css %}{% endblock %}
    {% block inline_css %}{% endblock %}
</head>
<body>
{% spaceless %}
    {% block body %}
    {% endblock %}

    {% block core_js %}
        <!-- External packages -->
        {#        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js" type="text/javascript"></script>#}
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"
                integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="{% static 'dartcms/js/lib/jquery-cookie/jquery.cookie.js' %}" type="text/javascript"></script>
        <script src="{% static 'dartcms/assets/boostrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'dartcms/assets/jasny-bootstrap/js/jasny-bootstrap.min.js' %}"
                type="text/javascript"></script>
        <script src="{% static 'dartcms/assets/jquery-modal/jquery-modal.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'dartcms/assets/pnotify/pnotify.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'dartcms/js/apps/base/navigation.js' %}" type="text/javascript"></script>
        <!-- End of external packages -->

        <!-- DartCMS packages -->

        <!-- End of DartCMS packages -->

        <script src="{% url 'dartcms:javascript-catalog' %}" type="text/javascript"></script>
    {% endblock %}

    {% block js %}{% endblock %}
    {% block inline_js %}{% endblock %}
{% endspaceless %}
</body>
</html>

dartcms/templates/dartcms/base/index.html
{% extends "dartcms/base/base.html" %}

{% load i18n static dartcms_helpers gravatar %}

{% block body %}
    <div class="wrapper">
        {% block wrapper %}
            <nav class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm" id="id-navmenu">
                <a class="navmenu-brand" href="#">
                    <img src="{% static 'dartcms/images/logo.png' %}"/>
                </a>
                <ul class="nav navmenu-nav">
                    <div class="user-info">
                        <div class="user-avatar">
                            <img src="{% gravatar_url request.user.email 50 %}" class="img img-circle"/>
                        </div>
                        <div class="user-meta">
                            <div class="user-name"><i class="fa fa-user"></i> {{ request.user }}</div>
                            {% if request.user.is_superuser %}
                                <span class="label label-danger">Admin</span>
                            {% elif request.user.is_staff %}
                                <span class="label label-info">Staff</span>
                            {% endif %}
                            &nbsp;<span class="label label-success">Online</span>
                        </div>
                    </div>
                    <li>
                        {% url 'dartcms:dashboard:index' as dashboard_index_url %}
                        <a href="{{ dashboard_index_url }}">
                            <i class="fa fa-home"></i> {% trans 'Dashboard' %}
                        </a>
                    </li>
                    {% for group in module_groups %}
                        {% if group.modules.all %}
                            <li class="dropdown {% if group.slug == active_group_slug %}open{% endif %}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa {{ group.fa }}"></i>
                                    {% if LANGUAGE_CODE == 'en' %}{{ group.name_en }}{% else %}
                                        {{ group.name }}{% endif %}
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu navmenu-nav" role="menu">
                                    {% for module in group.modules.all %}
                                        {% if module.is_enabled and module in request.user.module_set.all %}
                                            {% with module_url=dashboard_index_url|add:module.slug|add:"/" %}
                                                <li {% if module.slug == active_module_slug %}class="active"{% endif %}>
                                                    <a href="{{ module_url }}">
                                                        {% if LANGUAGE_CODE == 'en' %}
                                                            {{ module.name_en }}
                                                        {% else %}
                                                            {{ module.name }}
                                                        {% endif %}
                                                    </a>
                                                </li>
                                            {% endwith %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <li>
                        <a href="{% url 'dartcms:auth:logout' %}">
                            <i class="fa fa-sign-out"></i> {% trans 'Logout' %}
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="content">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <button type="button" class="navbar-toggle" data-toggle="offcanvas"
                                data-target="#id-navmenu" aria-expanded="false" data-canvas="body">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="{% url 'admin:index' %}"><i
                                            class="fa fa-cogs"></i>&nbsp;&nbsp;{% trans 'Django administration' %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'dartcms:users:change_password' pk=request.user.pk %}"><i
                                            class="fa fa-lock"></i>&nbsp;&nbsp;{% trans 'Change password' %}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="page-content">
                    <ol class="breadcrumb pull-left">
                        <li>
                            <i class="fa fa-sitemap"></i>
                        </li>
                        <li>
                            <a href="{{ dashboard_index_url }}">{% trans 'Dashboard' %}</a>
                        </li>
                        {% block breadcrumbs_current_path %}{% endblock %}
                    </ol>
                    <div class="clearfix"></div>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible"
                                 role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <i class="fa fa-info-circle"></i> {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% block page_content %}{% endblock %}
                </div>
            </div>
        {% endblock %}
    </div>
{% endblock %}